### PR TITLE
Fix Launchpad compilation error on OpenGL

### LINKED ISSUE #24: Launchpad fails to compile since update 2506
Launchpad no longer compiles when using ReShade with OpenGOAL ever since update 2506 (git bisect narrowed it to commit b68391ab728492d4a0bd68105f27756fc21c9469). The error message reads:

```
03:44:19:155 [20180] | ERROR | Failed to compile GLSL shader:
ERROR: 0:151: 'texel offset' : argument must be compile-time constant 
ERROR: 0:151: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

03:44:19:155 [20180] | ERROR | Failed to create graphics pipeline for pass 42 in technique 'MartysMods_Launchpad' in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_LAUNCHPAD.fx'!
```

**OpenGOAL version:** 0.3.1
**ReShade version:** 6.6.2.2083
**iMMERSE version:** 2506

I've re-tested with the newest version of ReShade (6.7.3) and iMMERSE Pro (2603) and get the same error.

OpenGOAL uses OpenGL for rendering. Using the Mesa Zink driver to translate to Vulkan allows Launchpad to compile, but has drawbacks including preventing me from excluding the HUD from effects like RTGI, making things look terrible.

Here's the full log:

```
03:44:07:485 [20180] | INFO  | Initializing crosire's ReShade version '6.6.2.2083' (64-bit) loaded from 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\OPENGL32.DLL' into 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\gk.exe' (0xB53F6DD7) ...
03:44:07:486 [20180] | INFO  | Registering hooks for 'user32.dll' ...
03:44:07:486 [20180] | INFO  | > Libraries loaded.
03:44:07:486 [20180] | INFO  | > Found 21 match(es). Installing ...
03:44:07:506 [20180] | INFO  | Registering hooks for 'C:\WINDOWS\system32\dinput.dll' ...
03:44:07:506 [20180] | INFO  | > Delayed.
03:44:07:507 [20180] | INFO  | Registering hooks for 'C:\WINDOWS\system32\dinput8.dll' ...
03:44:07:507 [20180] | INFO  | > Delayed.
03:44:07:507 [20180] | INFO  | Registering hooks for 'ws2_32.dll' ...
03:44:07:507 [20180] | INFO  | > Libraries loaded.
03:44:07:507 [20180] | INFO  | > Found 8 match(es). Installing ...
03:44:07:526 [20180] | INFO  | Registering hooks for 'C:\WINDOWS\system32\opengl32.dll' ...
03:44:07:526 [20180] | INFO  | > Delayed until first call to an exported function.
03:44:07:526 [20180] | INFO  | Registering hooks for 'openvr_api.dll' ...
03:44:07:526 [20180] | INFO  | > Delayed.
03:44:07:526 [20180] | INFO  | Initialized.
03:44:07:528 [20180] | INFO  | Redirecting wglChoosePixelFormat(hdc = 0000000036010F32, ppfd = 000000063CB4CEA0) ...
03:44:07:528 [20180] | INFO  | > Dumping pixel format descriptor:
03:44:07:528 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:528 [20180] | INFO  |   | Name                                    | Value                                   |
03:44:07:528 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:528 [20180] | INFO  |   | Flags                                   | 0x25                                    |
03:44:07:528 [20180] | INFO  |   | ColorBits                               | 24                                      |
03:44:07:528 [20180] | INFO  |   | DepthBits                               | 24                                      |
03:44:07:528 [20180] | INFO  |   | StencilBits                             | 8                                       |
03:44:07:528 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:528 [20180] | INFO  | Installing export hooks for 'C:\WINDOWS\system32\opengl32.dll' ...
03:44:07:528 [20180] | INFO  | > Found 360 match(es). Installing ...
03:44:07:562 [20180] | INFO  | Returning pixel format: 14
03:44:07:562 [20180] | INFO  | Redirecting wglSetPixelFormat(hdc = 0000000036010F32, iPixelFormat = 14, ppfd = 000000063CB4CEA0) ...
03:44:07:562 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:07:563 [20180] | INFO  | Redirecting wglCreateContext(hdc = 0000000036010F32) ...
03:44:07:563 [20180] | INFO  | > Passing on to wglCreateLayerContext:
03:44:07:563 [20180] | INFO  | Redirecting wglCreateLayerContext(hdc = 0000000036010F32, iLayerPlane = 0) ...
03:44:07:626 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:07:626 [20180] | INFO  | Redirecting wglDeleteContext(hglrc = 0000000000010000) ...
03:44:07:636 [20180] | INFO  | Redirecting wglChoosePixelFormat(hdc = FFFFFFFFC00110A9, ppfd = 000000063CB4CBF4) ...
03:44:07:637 [20180] | INFO  | > Dumping pixel format descriptor:
03:44:07:637 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:637 [20180] | INFO  |   | Name                                    | Value                                   |
03:44:07:637 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:637 [20180] | INFO  |   | Flags                                   | 0x25                                    |
03:44:07:637 [20180] | INFO  |   | ColorBits                               | 24                                      |
03:44:07:637 [20180] | INFO  |   | DepthBits                               | 24                                      |
03:44:07:637 [20180] | INFO  |   | StencilBits                             | 8                                       |
03:44:07:637 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:637 [20180] | INFO  | Returning pixel format: 14
03:44:07:637 [20180] | INFO  | Redirecting wglSetPixelFormat(hdc = FFFFFFFFC00110A9, iPixelFormat = 14, ppfd = 000000063CB4CBF4) ...
03:44:07:637 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:07:638 [20180] | INFO  | Redirecting wglCreateContext(hdc = FFFFFFFFC00110A9) ...
03:44:07:638 [20180] | INFO  | > Passing on to wglCreateLayerContext:
03:44:07:638 [20180] | INFO  | Redirecting wglCreateLayerContext(hdc = FFFFFFFFC00110A9, iLayerPlane = 0) ...
03:44:07:664 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:07:664 [20180] | INFO  | Redirecting wglChoosePixelFormatARB(hdc = FFFFFFFFC00110A9, piAttribIList = 000000063CB4CD40, pfAttribFList = 000000063CB4CCC4, nMaxFormats = 1, piFormats = 000000063CB4CBE8, nNumFormats = 000000063CB4CC1C) ...
03:44:07:664 [20180] | INFO  | > Dumping attributes:
03:44:07:665 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:665 [20180] | INFO  |   | Attribute                               | Value                                   |
03:44:07:665 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:665 [20180] | INFO  |   | WGL_DRAW_TO_WINDOW_ARB                  | TRUE                                    |
03:44:07:665 [20180] | INFO  |   | WGL_RED_BITS_ARB                        | 8                                       |
03:44:07:665 [20180] | INFO  |   | WGL_GREEN_BITS_ARB                      | 8                                       |
03:44:07:665 [20180] | INFO  |   | WGL_BLUE_BITS_ARB                       | 8                                       |
03:44:07:665 [20180] | INFO  |   | WGL_ALPHA_BITS_ARB                      | 8                                       |
03:44:07:665 [20180] | INFO  |   | WGL_DOUBLE_BUFFER_ARB                   | TRUE                                    |
03:44:07:665 [20180] | INFO  |   | WGL_DEPTH_BITS_ARB                      | 24                                      |
03:44:07:665 [20180] | INFO  |   | WGL_STENCIL_BITS_ARB                    | 8                                       |
03:44:07:665 [20180] | INFO  |   | WGL_ACCELERATION_ARB                    | 0x2027                                  |
03:44:07:665 [20180] | INFO  |   +-----------------------------------------+-----------------------------------------+
03:44:07:665 [20180] | INFO  | Returning pixel format(s): 14
03:44:07:665 [20180] | INFO  | Redirecting wglDeleteContext(hglrc = 0000000000020000) ...
03:44:07:671 [20180] | INFO  | Redirecting wglSetPixelFormat(hdc = 0000000071010F32, iPixelFormat = 14, ppfd = 000000063CB4CC98) ...
03:44:07:671 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:07:680 [20180] | INFO  | Redirecting wglCreateContext(hdc = 0000000071010F32) ...
03:44:07:680 [20180] | INFO  | > Passing on to wglCreateLayerContext:
03:44:07:681 [20180] | INFO  | Redirecting wglCreateLayerContext(hdc = 0000000071010F32, iLayerPlane = 0) ...
03:44:07:709 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:07:709 [20180] | INFO  | Redirecting wglCreateContextAttribsARB(hdc = 0000000071010F32, hShareContext = 0000000000000000, piAttribList = 000000063CB4CFC0) ...
03:44:07:709 [20180] | INFO  | Requesting core OpenGL context for version 4.3.
03:44:07:709 [20180] | INFO  | Redirecting wglCreateLayerContext(hdc = 0000000071010F32, iLayerPlane = 0) ...
03:44:07:713 [20180] | INFO  | Redirecting wglDeleteContext(hglrc = 0000000000030000) ...
03:44:07:718 [20180] | INFO  | Searching for add-ons (*.addon, *.addon64) in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1' ...
03:44:08:373 [20180] | INFO  | Redirecting RegisterClassW(lpWndClass = 000000063CB4C7D0 { "SDLHelperWindowInputCatcher", style = 0 }) ...
03:44:08:376 [20180] | INFO  | Redirecting RegisterClassExA(lpWndClassEx = 00007FF71344F110 { "SDL_HIDAPI_DEVICE_DETECTION", style = 0 }) ...
03:44:08:451 [20180] | INFO  | Installing delayed hooks for 'C:\WINDOWS\system32\dinput8.dll' (Just loaded via LoadLibrary('C:\Windows\System32\dinput8.dll')) ...
03:44:08:451 [20180] | INFO  | > Found 2 match(es). Installing ...
03:44:08:477 [ 8592] | INFO  | Redirecting RegisterClassExW(lpWndClassEx = 00007FF713473FF0 { "Message", style = 0 }) ...
03:44:08:565 [20180] | INFO  | Resizing device context 0000000071010F32 to 1920x1080 ...
03:44:08:565 [20180] | INFO  | Running on AMD Radeon RX 7800 XT.
03:44:08:846 [20180] | INFO  | Recreated runtime environment on runtime 000001844BC64710 ('C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\ReShade.ini').
03:44:08:865 [14816] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\Daltonize.fx' in 0.013000 s.
03:44:08:866 [17248] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\LUT.fx' in 0.014000 s.
03:44:08:866 [10348] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\DisplayDepth.fx' in 0.016000 s.
03:44:08:866 [ 5988] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\UIMask.fx' in 0.014000 s.
03:44:08:867 [10420] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\Deband.fx' in 0.016000 s.
03:44:08:874 [ 2240] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_CLARITY.fx' in 0.023000 s.
03:44:08:874 [15544] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_SHARPEN.fx' in 0.023000 s.
03:44:08:875 [20628] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_SOLARIS.fx' in 0.023000 s.
03:44:08:884 [ 8404] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_REGRADE.fx' in 0.033000 s.
03:44:08:884 [21920] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_MXAO.fx' in 0.033000 s.
03:44:08:884 [21176] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_EXPOSUREFUSION.fx' in 0.033000 s.
03:44:08:884 [13768] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_DEPTHOFFIELD.fx' in 0.033000 s.
03:44:08:884 [12276] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_SMAA.fx' in 0.034000 s.
03:44:08:886 [19004] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_INSIGHT.fx' in 0.035000 s.
03:44:08:893 [23400] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_LAUNCHPAD.fx' in 0.041000 s.
03:44:08:907 [22880] | INFO  | Successfully compiled 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_RTGI.fx' in 0.057000 s.
03:44:19:155 [20180] | ERROR | Failed to compile GLSL shader:
ERROR: 0:151: 'texel offset' : argument must be compile-time constant 
ERROR: 0:151: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


03:44:19:155 [20180] | ERROR | Failed to create graphics pipeline for pass 42 in technique 'MartysMods_Launchpad' in 'C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\reshade-shaders\Shaders\iMMERSE\MartysMods_LAUNCHPAD.fx'!
03:44:23:257 [20180] | INFO  | Destroyed runtime environment on runtime 000001844BC64710 ('C:\Users\mbmil\AppData\Local\Programs\OpenGOAL\versions\official\v0.3.1\ReShade.ini').
03:44:25:995 [20180] | INFO  | Redirecting wglDeleteContext(hglrc = 0000000000010001) ...
03:44:26:140 [20180] | INFO  | Exiting ...
03:44:26:140 [20180] | INFO  | Uninstalling 563 hook(s) ...
03:44:27:163 [20180] | INFO  | Finished exiting.
```

### PR DESCRIPTION
**Pull request by mikebm94**
Manually unrolls a loop in AlbedoMainPS() so an expression can be determined as a compile-time constant on OpenGL.

Fixes #24

### CODE REVIEW

**Comment by mikebm94** [comment]
Let me know if there's anything that needs cleaning up

**Comment by martymcmodding** [comment]
Sorry, I don't check this repo often, it's more of a public mirror than anything.

I'm glad you found the instruction that causes the problem, since last time I looked, I didn't find it, as I went off the logs from someone else because I don't have a OpenGL app to test, and the pass count depends on the screen resolution.

However, unrolling like that assumes I'd never want to change the offsets or kernel footprint, so I'd prefer it to remain a loop. tex2D with immediate offsets isn't really needed there though, this is likely saving a few nanoseconds only over simply offsetting the UV by float2(x,y) * BUFFER_PIXEL_SIZE. I tried to be elegant about it, alas. I'll update the shader next update cycle with the fix, so thanks again for finding it.
